name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11.5
          cache: "pip"
      - name: "installation"
        run: pip install -r requirements.txt
      - name: "black"
        run: black . --check --diff --color
      - name: "pytest"
        run: python -m pytes
